Use correct dependency versions in SPM
surfstudio/NodeKit pull request #104
Opened 2020-12-31 14:03 UTC by somenkovnikita

## Что сделано?
* После того как добавили Package.swift в CoreEvents билд сломался у всех проектов.
* Изменил на правильную на правильную версию

2021-01-11 06:14 UTC, Alelenka requested changes

2021-01-11 06:14 UTC, Alelenka commented on Package.swift
>          .package(url: "https://github.com/Alamofire/Alamofire", .exact("5.0.0-beta.6")),
Тут `5.0.0-beta.6`, а выше в `Package.resolved`  `5.0.0` - это норм?

2021-01-11 12:12 UTC, somenkovnikita commented on Package.swift
>          .package(url: "https://github.com/Alamofire/Alamofire", .exact("5.0.0-beta.6")),
Нет, не норм, это я топовый коммитер у мамы, исправил. Причина: коммит кода пока строит

2021-01-15 08:43 UTC, LastSprint approved these changes

2021-01-15 09:34 UTC, Alelenka approved these changes

2021-01-18 03:52 UTC, merged