Spt 1998 logger
surfstudio/NodeKit pull request #121
Opened 2024-03-20 09:05 UTC by mrandrewsmith

# What is done

- Улучшены generic в протоколах
- Убран базовый класс Node, протокол NodeProtocol переименован в Node
- Создан LoggingContext для записи логов внутри нод

2024-03-21 14:02 UTC, NullIsOne approved these changes

2024-04-11 07:46 UTC, Goldilocks97 requested changes

2024-04-11 07:46 UTC, Goldilocks97 commented on NodeKit/CacheNode/FirstCachePolicyNode.swift
>      ///   - next: Узел для чтения из кэша.
Кажется, что перепутаны названия аргументов и их описание

2024-04-11 07:46 UTC, Goldilocks97 commented on NodeKit/Utils/Logging/LoggingContext.swift
> +        guard var selfLog = self.log else {
Может, назвать currentLog?

2024-04-11 07:46 UTC, Goldilocks97 commented on NodeKitTests/Utils/LoggingContextTests.swift
> +    func testLog_whenOneItemAppending_therResultIsAppendedItem() async throws {
`therResultIs...` опечатался, `then`

2024-04-11 12:13 UTC, Goldilocks97 approved these changes

2024-04-12 11:10 UTC, chausovSurfStudio approved these changes

2024-04-12 11:10 UTC, chausovSurfStudio commented on NodeKitTests/Utils/LoggingContextTests.swift
> +
ух, понял)
предложение - где-то в комментах указать, что в силу особенностей поведения, описанных в документации, получится цепочка типа [1, 4, 3, 2], а то у меня отторжение в самом начале началось, когда к третьему логу добавляли второй, а потом третий к четвертому, а потом четвертый к первому))

2024-04-12 11:13 UTC, chausovSurfStudio commented on NodeKit/CacheNode/ETag/UrlETagReaderNode.swift
> +open class UrlETagReaderNode: Node {
а, совсем плохой вопрос, понял - отнаследоваться нельзя

2024-04-12 12:53 UTC, mrandrewsmith commented on NodeKit/CacheNode/UrlNotModifiedTriggerNode.swift
>          var logMessage = self.logViewObjectName
Как я понял из описания к методу, так и задумано. Как на самом деле должно работать я не в курсе, потому что эта нода нигде не используется

2024-04-12 12:54 UTC, mrandrewsmith commented on NodeKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "1d2e6911b0388532b33f83466feee8deadacbc6241719180eb45fd871a5091ac",
В  ПР, где починен Codecov Package.resolved удален, так что этого уже нет, просто в другой ветке.

2024-04-12 15:00 UTC, chausovSurfStudio commented on NodeKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "1d2e6911b0388532b33f83466feee8deadacbc6241719180eb45fd871a5091ac",
отлично 👍

2024-04-16 10:17 UTC, mrandrewsmith commented on NodeKit/CacheNode/UrlNotModifiedTriggerNode.swift
>          var logMessage = self.logViewObjectName
Мне кажется это задумывалось не много по другому. У нас цель всех nextNode, чтобы в конечном итоге полчить Json и вернуть его по цепочке назад, где он будет преобразован в модель, если требуется. В случае UrlNotModifiedTriggerNode, при 304 ошибке мы уже вытаскиваем готовый Json из кэша и возвращаем его назад. Если бы кэш нам возвращал не Json, а UrlDataResponse, тогда бы мы вызывали next, после чтения из кэша.

2024-04-16 10:19 UTC, merged