SPT-1998 Swift cuncurrency support
surfstudio/NodeKit pull request #122
Opened 2024-03-26 14:27 UTC by mrandrewsmith

Добавлена поддержка Swift Concurrency. 

Созданы новые протоколы:
- AsyncNode - нода, которая умеет ассинхронно выполнять обработку данных и возвращает результат.
- AsyncStreamNode - нода, которая умеет ассинхронно выполнять обработку данных и превращает результат в асинхронный поток.

Поправлены тесты для прохождения ci. Основные работы по тестам будут в следующих ПР.

2024-03-27 06:19 UTC, NullIsOne requested changes
Несколько замечаний по тестам (в основном некритичные) и много опечаток в доке (возможно не все нашел)

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/ResponseProcessingLayer/ResponseProcessorNode.swift
> +                metrics: nil, // ?? почему nil
> // ?? почему nil
 // почему -1?

Тоже интересно почему? 
Даже если это копипаста со старой реализации, лучше постараться разобраться и добавить более емкие комментарии содержащие ответ.

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/ResponseProcessingLayer/ResponseHttpErrorProcessorNode.swift
> +    /// Сопосотавляет HTTP-коды с заданными и в случае их несовпадения передает управление дальше.
```suggestion
    /// Сопоставляет HTTP-коды с заданными и в случае их несовпадения передает управление дальше.
```

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/ResponseProcessingLayer/ResponseDataParserNode.swift
> +    /// - Parameter data: Модель овтета сервера.
```suggestion
    /// - Parameter data: Модель ответа сервера.
```

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/RequestProcessingLayer/MultipartRequestCreatorNode.swift
> +    /// Конфигурирует низкоуровненвый запрос.
```suggestion
    /// Конфигурирует низкоуровневый запрос.
```

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/RequestBuildingLayer/URLQueryInjectorNode.swift
> +    /// - SeeAlso: `URLQueryInjectorNodeError`
При ссылке на другой файл можно в комментах ссылку оформить
- по-старому https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/Links.html
- в DocC стиле должно что-то вроде этого сработать
> \`\`URLQueryInjectorNodeError\`\`

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/InputProcessingLayer/DTOEncoderNode.swift
> +    /// Если при конвертирвоании произошла ошибка - прерывает выполнение цепочки.
```suggestion
    /// Если при конвертировании произошла ошибка - прерывает выполнение цепочки.
```

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/DTOProcessingLayer/RawEncoderNode.swift
> +    /// Если при конвертирвоании произошла ошибка - прерывает выполнение цепочки.
```suggestion
    /// Если при конвертировании произошла ошибка - прерывает выполнение цепочки.
```

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Layers/ConfigurationLayer/ChainConfiguratorNode.swift
> +    /// Созздает асинхронный контект с очередью `beginQueue`,
```suggestion
    /// Создает асинхронный контекст с очередью `beginQueue`,
```

2024-03-27 06:19 UTC, NullIsOne commented on NodeKit/Core/Node/NodeResult.swift
> +    /// - Parameter customError: Ошибка, которая будет передаваться в failure вместо Exeception
Когда надо описать несколько параметров в доке работает такая структура
```
/// - Parameters:
///  - customError: ..
///  - function: ..
```
Только отступы надо перепроверять несколько раз, чтобы в инспекторе весь док-коммент правильно подсвечивался.

2024-03-27 10:44 UTC, mrandrewsmith commented on NodeKitTests/UnitTests/MockerIntegration/MockerProxyConfigNodeTests.swift
> +        XCTAssertEqual(try nextNodeResult.get().metadata, expectedNextNodeResult.metadata)
Если тест помечен как throws, то ошибки в тестах при try не приводят к остановке тестов. Тест, где произошла ошибка будет красный, остальные тесты продолжат выполнение.

При использовании try вместо try?, текст ошибки в тестах боллее понятен.

2024-03-27 10:45 UTC, mrandrewsmith commented on NodeKitTests/UnitTests/MockerIntegration/MockerProxyConfigNodeTests.swift
> +        XCTAssertEqual(try nextNodeResult.get().metadata, expectedNextNodeResult.metadata)
Я поправлю nextNodeResult?.metadata, чтобы привести к общему виду

2024-03-27 10:49 UTC, mrandrewsmith commented on NodeKit/Layers/ResponseProcessingLayer/ResponseProcessorNode.swift
> +                metrics: nil, // ?? почему nil
Я сделаю пометку себе, но вряд ли в этом пр что то будет сделано по этому поводу.

2024-04-02 05:54 UTC, NullIsOne approved these changes

2024-04-11 08:27 UTC, Goldilocks97 approved these changes

2024-04-11 08:27 UTC, Goldilocks97 commented on NodeKit/Layers/RequestProcessingLayer/RequestCreatorNode.swift
> +    /// Конфигурирует низкоуровненвый запрос.
`низкоуровненвый` опечатка

2024-04-11 08:27 UTC, Goldilocks97 commented on NodeKit/Core/Node/NodeResult.swift
> +    @inlinable func asyncFlatMap<NewSuccess>(
А можешь объяснить, пожалуйста, в чем идея называть `flat`, а не просто `map`?

2024-04-11 12:10 UTC, mrandrewsmith commented on NodeKit/Core/Node/NodeResult.swift
> +    @inlinable func asyncFlatMap<NewSuccess>(
Вызывая flatMap ты можешь вернуть .failure даже при .success результате, вызывая map при .success возвращается только .success.

2024-04-12 14:53 UTC, chausovSurfStudio reviewed
тесты не глядел, потому уже с другими тестами гляну

не помню, было ли что-то критичное в комментах, кажется как будто если где-то и были неточности - ты тестами потом найдешь) так что если ничего критичного и работа будет блочиться - можешь мержить

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/RequestProcessingLayer/RequestSenderNode.swift
> +        task?.cancel()
хм... у нас в concurrency варианте в self.task ничего не записывалось - в этот момент у нас точно есть что-то, что можно отменить? (сравни 59 и 125 строки)

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/ResponseProcessingLayer/ResponseProcessorNode.swift
> +                metrics: nil, // ?? почему nil
тоже интересно стало))

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/Utils/AccessSafe/TokenRefresherActor.swift
> +    func update(tokenRefreshChain: some AsyncNode<Void, Void>)
не уверен в необходимоси такой фичи, но если была уже в TokenRefresherNode - ну, допустим, океей)

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/Utils/AccessSafe/TokenRefresherActor.swift
> +    func update(tokenRefreshChain: some AsyncNode<Void, Void>)
только коммент к методу поправить)

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/Utils/AccessSafe/TokenRefresherActor.swift
> +        return await task.value
как красиво и просто теперь можно такие вещи сделать 🔥

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/Utils/AccessSafe/TokenRefresherNode.swift
>  }
правильно же понимаю, что в будущем все эти мутки с очередями и флагами выпилится и останется один только actor?

2024-04-12 14:53 UTC, chausovSurfStudio commented on NodeKit/Layers/Utils/AccessSafe/TokenRefresherNode.swift
>  }
когда будешь CoreEvents с корнями выдирать?

2024-04-16 10:21 UTC, mrandrewsmith commented on NodeKit/Core/Node/NodeResult.swift
> +    ) async -> Result<T, Error> {
Забыл тут поправить. Изначально NodeResult не было)

2024-04-16 10:59 UTC, mrandrewsmith commented on NodeKit/CacheNode/ETag/UrlETagSaverNode.swift
> +            let urlAsKey = url.withOrderedQuery()
Да, вероятно ошибка старой реализации. Если SaverNode запишет tag для запроса с URL с параметрами, то Reader его не прочитает. Исправлю.

2024-04-16 11:05 UTC, mrandrewsmith commented on NodeKit/CacheNode/ETag/UrlETagSaverNode.swift
> +            return .success(())
Хороший вопрос. Видимо ошибка в старой реализации. Судя по комментариям все равно должен вызваться next. Поправлю.

2024-04-16 11:08 UTC, mrandrewsmith commented on NodeKit/CacheNode/UrlCacheReaderNode.swift
> +            return .failure(BaseUrlCacheReaderError.cantLoadDataFromCache)
Да, с async методами несколько сложнее в этом плане, мы не можем ничего не вернуть.

2024-04-16 11:10 UTC, mrandrewsmith commented on NodeKit/Encodings/UrlJsonRequestEncodingNode.swift
> +        return URLEncoding.default
Дело привычки. Но если писать через if, то тут можно else опустить.

2024-04-16 11:12 UTC, mrandrewsmith commented on NodeKit/Layers/ConfigurationLayer/ChainConfiguratorNode.swift
> +        return await next.process(data, logContext: logContext)
SwiftConcurrency и GCD это две разные технологии, которые никак не связаны.  Поэтому beginQueue/endQueue тут не будут работать. Я их выпилил в следующих ПР.

2024-04-16 11:13 UTC, mrandrewsmith commented on NodeKit/Layers/InputProcessingLayer/VoidIONode.swift
> +            let result = Context<Void>()
В каком то ПР я это правил, но поправлю еще тут.

2024-04-16 11:34 UTC, mrandrewsmith commented on NodeKit/Layers/RequestProcessingLayer/RequestSenderNode.swift
> +        log += "Request sended!"
Тут есть сложности c многопоточностью, чтобы так просто менять log в nodeResponse. Но можно исправить в методе process.

2024-04-16 11:36 UTC, mrandrewsmith commented on NodeKit/Layers/RequestProcessingLayer/RequestSenderNode.swift
> +        task?.cancel()
Исправлено в пр с тестами. Там добавлен актор для хранения таски. И в ноде через актор таска останавливается.

2024-04-16 11:39 UTC, mrandrewsmith commented on NodeKit/Layers/Utils/AccessSafe/TokenRefresherNode.swift
>  }
Да, флагов и очередей не будет. CoreEvents удален с ПР c удалением Legacy.

2024-04-16 11:46 UTC, mrandrewsmith commented on NodeKit/Layers/ResponseProcessingLayer/ResponseProcessorNode.swift
> +                metrics: nil, // ?? почему nil
На сколько я понял параметры metrics и serializationDuration нигде не используются. Могу предположить, что metrics nil, потому что apple сделали init URLSessionTaskMetrics depricated. Метрики теперь можно получить только в URLSessionDataDelegate. Мне кажется их можно просто удалить.

2024-04-16 16:03 UTC, chausovSurfStudio commented on NodeKit/Encodings/UrlJsonRequestEncodingNode.swift
> +        return URLEncoding.default
это тоже дело привычки)

2024-04-16 16:23 UTC, merged