SPT-1998 Поддержка combine
surfstudio/NodeKit pull request #123
Opened 2024-04-01 10:22 UTC by mrandrewsmith

# Что сделано

- Добавлена возможность оборачивать любую ноду в CombineNode, у которой можно запросить publisher.
- Publisher работает по аналогии с Observer, то есть при новой подписке будет передаваться предыдущее значение, полученное нодой при вызове метода process.
- Написаны юнит тесты на связки AsyncNode -> CombineNode, AsyncStreamNode -> CombineNode.

# На что обратить внимание

При использовании CombineNode над AsyncStreamNode есть вероятность пропустить часть данных, если подписка на них происходит до вызова метода process и когда метод process отрабатывает быстро. Если важно не пропустить данные, следует подписываться до вызова метода process.

# Пример использования

```swift
ChainConfigurator()
    .build()
    .combineNode()
    .eraseToAnyPublisher()
    .sink {
    }
```

2024-04-01 12:21 UTC, NullIsOne requested changes

2024-04-01 12:21 UTC, NullIsOne commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    private let subject = CurrentValueSubject<NodeResult<Output>?, Never>(nil)
Почему был выбран CurrentValueSubject?
Он хранит прошлое значение и возвращает его новым подписчикам. 
В контексте клиент-серверного взаимодействия это не то, что ожидаешь от сетевого слоя. 
Он получается ответы и ошибки будет кэшировать.

Может переделать на `PassthroughSubject`?

2024-04-01 12:21 UTC, NullIsOne commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    public func eraseToAnyPublisher() -> AnyPublisher<NodeResult<Output>, Never> {
А как быть, когда надо получить ошибку?
Можем ли мы тут не затирать ошибку до типа `Never`?

Думаю на уровне ноды не совсем корректно затирать до AnyPublisher.
Запрос и его обработка нодой это разовое асинхронное действие. В Combine для этого есть publisher типа `Future`

2024-04-01 18:45 UTC, mrandrewsmith commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    private let subject = CurrentValueSubject<NodeResult<Output>?, Never>(nil)
Сделано это с целью повторить старое поведение Context. Но нет такого Subject, который прошлое значение затирает, если оно было получено, поэтому выбрал CurrentValueSubject. Можно вернуть PassthroughSubject, но в таком случае если данные пойдут, до того как подпишешься, пропустишь часть данных.
<img width="605" alt="Screenshot 2024-04-01 at 20 41 40" src="https://github.com/surfstudio/NodeKit/assets/87606864/6ad00d7a-eb25-4f4f-a78b-85ae3d4a56fd">

2024-04-01 18:56 UTC, mrandrewsmith commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    public func eraseToAnyPublisher() -> AnyPublisher<NodeResult<Output>, Never> {
Ошибка будет лежать в NodeResult, который может быть success или falure с ошибкой. 

Так было сделано пототому, что у нас есть ноды, которые возвращают несколько значений и мы можем получить несколько ошибок. А если поменять вместо Never сделать Error и получать ошибку в completed, то после первой ошибки все остальные данные проигнорируются.

Future не умеют работать с потоком данных, они возвращают только одно значение.

2024-04-02 05:39 UTC, NullIsOne commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    public func eraseToAnyPublisher() -> AnyPublisher<NodeResult<Output>, Never> {
Хорошо. Ошибку в результате даже удобнее обрабатывать, можно так, но сделать шорт операторы, которые будут nodeResult в результат или ошибку маппить. Чтобы это по проекту не расплывалось и сетевой слой не зависел от изменений в NodeResult.

2024-04-02 05:39 UTC, NullIsOne commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    private let subject = CurrentValueSubject<NodeResult<Output>?, Never>(nil)
Это выглядит как смешивание подходов. Когда мы трансформируем ноду в Combine, мы хотим добавить обработчик через подписку. 
Поддерживать отложенные обработчики onCompleted/onError от старого обзервера это попытка усидеть на двух стульях.

Почему бы не попробовать возвращать `Publisher` в результате вызова `process`?
Это же сделает невозможным проблемы с подпиской невовремя.

2024-04-02 05:48 UTC, NullIsOne commented on NodeKit/Core/Node/Combine/CombineNode.swift
> +    public func eraseToAnyPublisher() -> AnyPublisher<NodeResult<Output>, Never> {
А нельзя ли отдельно обрабатывать AsyncNode с одним результатом и AsyncStreamNode который возвращает поток?

2024-04-04 11:43 UTC, NullIsOne approved these changes

2024-04-04 11:43 UTC, NullIsOne commented on NodeKit/Core/Node/Combine/AsyncCombineNode.swift
> +    public func nodeResultPublisher(for data: Input, on scheduler: some Scheduler, logContext: LoggingContextProtocol) -> AnyPublisher<NodeResult<Output>, Never> {
🔥 
Вот такой подход мне нравится.
Удобно будет использовать 👍

2024-04-11 10:43 UTC, Goldilocks97 approved these changes

2024-04-11 10:43 UTC, Goldilocks97 commented on NodeKit/Core/Node/Async/AsyncNode.swift
> +/// Протокол наследованный от CombineNode, добавляющий подход преобразования входных данных в результат с помощью SwiftConcurrency.
```suggestion
/// Протокол, наследованный от CombineNode, добавляющий подход преобразования входных данных в результат с помощью SwiftConcurrency.
```

2024-04-19 15:02 UTC, chausovSurfStudio approved these changes

2024-04-24 09:00 UTC, merged