SPT-1998 Обновление проекта с примерами
surfstudio/NodeKit pull request #130
Opened 2024-04-16 09:36 UTC by mrandrewsmith

# Что сделано

- SPM NodeKit вынесен в отдельную папку. Теперь Example и NodeKit лежит на одном уровне.
- Удалил не используемые файлы и папки, по типу Gemfile, ci с неиспользуемыми скриптами и старый сервер на Go.
- Обновил Example проект. Починил старую реализацию экранов логина и пагинации, плюс добавил экран со списком примеров и пример с ожиданием группы запросов. 
- Поправил NodeKit в местах, где было не удобно использовать. Например не много переработан AsyncIterator.

# Как проверить

- Открыть проект Expample

2024-04-17 09:21 UTC, NullIsOne requested changes
Из критичного на мой взгляд нерабочие картинки в примере и неканон использование rddm. (Выглядит местами как legacy код версии 5, хотя затянута 7.4)

2024-04-17 09:21 UTC, NullIsOne commented on Example/Example/Features/PaginationFeature/Cells/PaginationCellGenerator.swift
> +class PaginationCellGenerator {
Генератор не нужен.
Можно привести ячейку к ConfigurableItem и тогда станет доступен базовый.
`PaginationCell.rddm.baseGenerator(...`

2024-04-17 09:21 UTC, NullIsOne commented on Example/Example/Features/PaginationFeature/Subviews/LoadingView.swift
> +    func showProgress(_ isLoading: Bool) { }
В чем смысл пустой реализации LoadingView?
Плагин rddm добавляет эту вьюшку в футер, чтобы показать загрузку следующей пачки.
Пустой будет только лишь передавать сигнал о том что мы долистали.

Сейчас пример немножко оторван от реальности.
https://github.com/surfstudio/NodeKit/assets/28707156/597a9ce1-6d54-4122-b782-e59476e56757
При прокрутке мелькают индикаторы загрузки из ячеек `PaginationCell`, но у меня почему-то изображения после загрузки так и не отображаются. Надо бы поправить эту ячейку, а вместо индикатора загрузки изображения шиммеры простенькие затянуть. Вроде были в iOS-Utils.

2024-04-17 09:21 UTC, NullIsOne commented on Example/Example/Flows/FeatureListFlow/Cells/FeatureCellGenerator.swift
> +class FeatureCellGenerator {
Аналогично. 
Ненужный кастом-генератор.
Достаточно сделать `FeatureCell: ConfigurableItem` 
Обработка тапа на ячейку через didSelect базового генератора и плагин `selectable`
Подсветка по нажатию через `HighlightableItem` и плагин `highlightable`

См. примеры в RDDM.

2024-04-17 15:35 UTC, mrandrewsmith commented on Example/Example/Features/PaginationFeature/Subviews/LoadingView.swift
> +    func showProgress(_ isLoading: Bool) { }
LoadingView не реализовывал потому что с Loading индикатором изображений конфликтовало бы и визуально было бы сложно отличить. Но если затянуть шиммер, то в целом можно добавить индикатор в LoadingVIew.

Странно, у меня картинки подгружаются. Может из России сервис с картинками не доступен? Попробуй зайти на https://picsum.photos/200/300

2024-04-18 06:46 UTC, NullIsOne commented on Example/Example/Features/PaginationFeature/Subviews/LoadingView.swift
> +    func showProgress(_ isLoading: Bool) { }
> Странно, у меня картинки подгружаются. Может из России сервис с картинками не доступен? Попробуй зайти на https://picsum.photos/200/300

Да. Он заблочен похоже(
https://loremflickr.com работает
`https://loremflickr.com/320/240?random=1`
Можно его заюзать.

2024-04-19 09:00 UTC, NullIsOne approved these changes

2024-04-19 15:56 UTC, chausovSurfStudio commented on Example/Example/Features/PaginationFeature/Cells/PaginationCell.swift
> +import AlamofireImage
а не будет ли это изобретением велосипеда?) идея то в целом интересная, но не повторяет ли это существующие решения, прост на новый лад?

2024-04-22 14:51 UTC, chausovSurfStudio approved these changes
еще есть такое предложение - немного изменить структуру

сейчас что немного покоробило: есть Example-проект, есть локальные зависимости, есть сторонние зависимости. При этом локальные разделяются на непосредственно саму либу (NodeKit и его ThirdParty), и на "модули" самого проекта. Но все это лежит вместе в одной кучке(

<img width="333" alt="Снимок экрана 2024-04-22 в 17 41 56" src="https://github.com/surfstudio/NodeKit/assets/8776643/eebbc0d8-f110-446f-93a5-9e665c35bd87">

что если часть из них, которые непосредственно "модули" самого Example-проекта (MockServer, Services, Models), внести в проект - типа вот как тут

<img width="411" alt="Снимок экрана 2024-04-22 в 17 42 59" src="https://github.com/surfstudio/NodeKit/assets/8776643/47f292e7-3a9a-474e-b9f1-ff32e70b6cdf">

ну чтобы явно было видно, что вот модули проекта - да, они в отдельном пакете, но это все еще example, можно его менять, в вашем проекте в целом будет примерно так же. А все что ниже - это уже сторонние либы, да, часть из них локальные, но представьте что это черная коробка и не обращайте внимания на них.

Еще - возможно было бы полезно как-то иметь возможность изменять интервал, через который приходят ответы от мокового сервака. Я пока код не посмотрел - так и не понял, где там пагинация и как она работает, все моментально выполняется)

В остальном, помню какой тут бардак был раньше - и сейчас прям симпатично стало, работа оч большая проведена 💪

2024-05-02 07:35 UTC, mrandrewsmith commented on NodeKit/NodeKit/Utils/AsyncIterator/AsyncPagerIterator.swift
> +        self.dataProvider = dataProvider
Отмена идет через таску, итератор не имеет доступ таски, которую создали извне. Если надо отменить запрос, то следует сохранить таску, внутри которой будет вызван next, и при необходимости вызвать у нее cancel.

2024-05-02 07:38 UTC, mrandrewsmith commented on NodeKit/NodeKit/Utils/AsyncIterator/AsyncPagerIterator.swift
> +                currentState.hasNext = false
Согласен, тут лишнее.

2024-05-03 07:41 UTC, NullIsOne commented on NodeKit/Package.swift
> +            targets: ["NodeKit"]
Отмечу, что это перемещение `Package.swift → NodeKit/Package.swift` намертво отключает возможность подключения пакета по ветке или коммиту.
SPM ищет Package.swift в корне репозитория. И никак ему в клиентском package.swift или pbxproj не сказать иначе..

Это ок, если мы хотим релизить сборки, но пока что вот неожиданно наткнулся на такой неприятный момент при попытке использовать последние несмердженные наработки.

2024-05-06 13:04 UTC, chausovSurfStudio commented on NodeKit/Package.swift
> +            targets: ["NodeKit"]
в целом - ничего не имею против такой структуры, чтобы проект лежал сразу в корне, а example в своей папке

типа такого (прости @mrandrewsmith если где-то тебя сам подтолкнул к таком, но по идее вот как на картинке ожидал структуру, потом подумал что "а и хрен с ними, пусть так остается, если работает", но аргумент от Никиты - аргументный, затрудняет быструю проверку тех или иных правок...)
<img width="285" alt="Снимок экрана 2024-05-06 в 16 01 34" src="https://github.com/surfstudio/NodeKit/assets/8776643/7de4a953-eb15-4ac4-878d-462d85a8924e">

2024-05-07 05:17 UTC, mrandrewsmith commented on Example/Services/Services/PaginationService/PaginationContentDataProvider.swift
> +            .set(session: NetworkMock().urlSession)
Да, я потом добавлю в документацию

2024-05-07 10:15 UTC, chausovSurfStudio commented on NodeKit/Package.swift
> +            targets: ["NodeKit"]
будем считать вопрос закрытым)

2024-05-07 10:19 UTC, chausovSurfStudio commented on Example/Example/Features/PaginationFeature/Cells/PaginationCell.swift
> +import AlamofireImage
создал как issue на будущее, пока не в приоритете
https://github.com/surfstudio/NodeKit/issues/136

2024-05-07 11:09 UTC, chausovSurfStudio approved these changes
сливай 🎉

2024-05-07 11:42 UTC, merged