SPT-1998 Мелкий рефакторинг + моки на билдер
surfstudio/NodeKit pull request #133
Opened 2024-05-02 16:08 UTC by mrandrewsmith

# Что сделано

- Добавлены структуры-обертки AnyAsyncNode и AnyAsyncStreamNode в связи с тем, что компилятор не может правильно зарезолвить типы при использование any AsyncNode в билдере. При этом использовать some AsyncNode мы не можем, так как some не поддерживается в протоколах и нельзя наследовать методы класса, которые возвращают some.
- Добавлены методы eraseToAnyNode, которые оборачивают ноду в AnyAsyncNode или AnyAsyncStreamNode.
- Не много изменен билдер.
- Написаны моки на билдеры. Теперь можно передавать в сервис протокол ChainBuilder, а в тестах менять на мок и стаббать ноды.

2024-05-03 06:30 UTC, NullIsOne reviewed
Немного вопросов

2024-05-03 06:30 UTC, NullIsOne commented on NodeKit/NodeKit/Chains/ServiceChainProvider.swift
> +open class URLServiceChainProvider: ServiceChainProvider {
Тут тоже документации не хватает.
Замысел с разделением chains по типам Output понятен, но с другой стороны в старом `UrlServiceChainBuilder` было всего 2 метода
- `urlResponseProcessingLayerChain` для обработки ответа
- `requestTrasportChain` для обработки запроса

Теперь же как будто в 2 раза больше методов стало)
Надо обязательно какой-нибудь migration guide написать для лучшего переваривания этого.

2024-05-03 06:30 UTC, NullIsOne commented on NodeKit/NodeKit/Chains/ServiceChainProvider.swift
> +    open func provideRequestMultipartChain() -> any AsyncNode<URLRequest, Json> {
По логике должен быть также `provideResponseMultipartChain`, или нет?

2024-05-03 11:06 UTC, mrandrewsmith commented on NodeKit/NodeKit/Chains/ChainBuilder.swift
> +    open func requestRouterNode<Raw, Output>(
Да, идея в том, чтобы снизить дублируещие ноды и добиться меньшего числа переопределений. Документацию добавлю.

2024-05-03 11:08 UTC, mrandrewsmith commented on NodeKit/NodeKit/Chains/ServiceChainProvider.swift
> +    open func provideRequestMultipartChain() -> any AsyncNode<URLRequest, Json> {
По логике да, но у него такая же реализация, как и provideResponseJsonChain, могу добавить метод provideResponseMultipartChain и внутри вызвать provideResponseJsonChain, чтобы было понятнее.

2024-05-03 11:09 UTC, mrandrewsmith commented on NodeKit/NodeKit/Chains/ServiceChainProvider.swift
> +open class URLServiceChainProvider: ServiceChainProvider {
Добавлю описание. Да методов теперь больше, так как мы поддерживаем 3 типа цепочек, для Json, Data и Multipart

2024-05-06 03:24 UTC, NullIsOne commented on NodeKit/NodeKit/Chains/ServiceChainProvider.swift
> +    open func provideRequestMultipartChain() -> any AsyncNode<URLRequest, Json> {
Да, думаю так будет удобнее для кастомизации multipart цепочки.

2024-05-07 05:20 UTC, mrandrewsmith commented
Добавлен метод merge, для двух AsyncNode. Позволяет смержить две AsyncNode с одинаковыми Input и Output в AsyncStreamNode.

2024-05-07 06:10 UTC, NullIsOne approved these changes
Пока не попробовал метод с MergedNode для создания цепочки, но по основному содержанию в ПР могу поставить аппрув.

2024-05-07 06:10 UTC, NullIsOne commented on NodeKit/NodeKit/CacheNode/FirstCachePolicyNode.swift
> +    public typealias CacheReaderNode = AsyncNode<URLNetworkRequest, Json>
С новым`MergedAsyncStreamNode` эту ноду можно упразднить и встраивать кэширование как mergedNode где первый это CacheReader, а второй это NextProcessor.

2024-05-07 12:54 UTC, NullIsOne requested changes

2024-05-07 12:54 UTC, NullIsOne commented on NodeKit/NodeKitMock/Builder/ChainBuilderMock.swift
> +    public var stubbedBuildWithInputOutputResult: AsyncNodeMock<Any, Any>!
@mrandrewsmith 
Начал прикручивать в проект и попробовал написать пару тестов.
Тут `Any` не работает.
Если установить сюда например мок
```
let resultMock = AsyncNodeMock<Any, Any>()
chainBuilderMock.stubbedBuildWithInputOutputResult = resultMock
```
то упадет при unwrap `as!` ниже.
Если попытаться указать типы, то не даст устнаовить такой мок
```
let resultMock = AsyncNodeMock<AuthByCodeRequestEntity, AuthByCodeResponseEntity>()
chainBuilderMock.stubbedBuildWithInputOutputResult = resultMock
```
> /Users/korobeinikov/Documents/GitHub/swiftUI-core/Modules/Feature/NetworkServices/Tests/NetworkServicesTests/AuthServiceTests.swift:69:60 Cannot assign value of type 'AsyncNodeMock<AuthByCodeRequestEntity, AuthByCodeResponseEntity>' to type 'AsyncNodeMock<Any, Any>'

2024-05-07 13:13 UTC, NullIsOne commented on NodeKit/NodeKitMock/Builder/ChainBuilderMock.swift
> +    public var stubbedBuildWithInputOutputResult: AsyncNodeMock<Any, Any>!
И с <Void, Any> таже проблема.
Можешь посмотреть как я их пытаюсь использовать в тестах https://github.com/surfstudio/swiftUI-core/pull/17/files

2024-05-13 12:40 UTC, mrandrewsmith commented on NodeKit/NodeKitMock/Builder/ChainBuilderMock.swift
> +    public var stubbedBuildWithInputOutputResult: AsyncNodeMock<Any, Any>!
Исправлено

2024-05-13 12:44 UTC, NullIsOne approved these changes
Проверил моки chain после правок.
Теперь они работают и не падают.

2024-05-22 14:59 UTC, chausovSurfStudio approved these changes
тесты и моки честно пролистал - надеюсь на вас с Никитой)

2024-05-22 14:59 UTC, chausovSurfStudio commented on NodeKit/NodeKit/CacheNode/URLCacheReaderNode.swift
> +        self.needsToThrowError = needsToThrowError
а зачем оно добавилось, если никак не используется?

2024-05-22 14:59 UTC, chausovSurfStudio commented on NodeKit/NodeKit/Layers/ResponsePostprocessingNode/Models/URLProcessedResponse.swift
> -    public var serializationDuration: TimeInterval {
аа, понял, таинственные nil и -1! эх, задумка хорошая была, надо запомнить на будущее, если вдруг какие-то метрики по проектам начнем собирать, в том числе и по работе с сервис слоем

2024-05-22 14:59 UTC, chausovSurfStudio commented on NodeKit/NodeKit/Chains/URLChainConfigModel.swift
> +public struct URLChainConfigModel {
немного неожиданный вопрос - а эта структура вообще где-то используется?) а то я что-то кроме объявления и тестов больше её нигде не вижу...

2024-05-24 10:30 UTC, mrandrewsmith commented on NodeKit/NodeKit/Chains/URLChainConfigModel.swift
> +public struct URLChainConfigModel {
Не используется) По хорошему провести бы ревизию, понять что устарело и можно удалять. Думаю это не единственный кандидат на удаление

2024-05-24 10:47 UTC, merged